client:
  properties:
    prop1: presto
    prop2: '{cipher}AQBMjpQ3HUNyR1b0fuwj/olvFOj5KaBWv0hs9Ib7xa1s6/4Zqt+AS05Y+v6Q8Hl5y7+jE0QaDjh1rK9jbce/gGrlmCXkGoDjSJGpw5yg/z7wY0zgi712pluwzXBqMbWgALc7sKJnli8fFCLzcKPl3551Xtc/Y/LrkEp1xCSE1iP+VonTtHBj/NBOBTx7p2x8JNqrdgnfXed+EJUcIgozmk9NblWE5nA4L8YY1d2K8JoOa60CNcAZo5XkK++HLg2lLiPC+s9fMJFXzr479LsL47Od4ThsXweZVtKkRzgS9vkWukKle5bC/6oOMOdaiRbFmVW9ozEyyfhEfjRVbJiwkWB3Bdlrr7EiP87ifJ6HIDpvV4IcOKk/9UVbTtx80QK0dy4='