client:
  properties:
    prop1: grave12
    prop2: '{cipher}AQCcO1C74M99ncFk37iqSY7KW4K7SSSCZRVDjgc8su9YApNvKQSAjhm3sSy/tgUHGG4et2VYbbMofDuYTS4Ps+XZWuSf5h38+5G73Sn1qcXjGO4rfYx168KOVM6HCJyM43lEO/+43U/PnG6rZ7mZAl+OYy8hwhlryqnLYGVcmDYaKWzrZces4UsQB2orrAPdWEdstq+iGBFK4cQZeb3DSmyxe4ZdRlxUfLzf3kazA7WtuZK0vRsXadgQNXw0+qQnZ8P0rEBPS+WbF8qAh0f+tbgmLK/OvTJsGntOe1Syj+RQcj/ztk4PJiLBJOeYcXvpDxFhGqbgTbhJziW2+bWPKCIaD63pqsKufEsHL76KiK2TU1EC6O+KZ47AGvRFdshmGIc='
