client.first.test1: Default App
server:
  port: 8081
spring.cloud.bus.enabled: true

spring:
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: spring-bus-test
          group: test-client